#!/usr/bin/env bash
#
# Bring EditForge up locally for DEVON. One command, from nothing to a studio
# on this machine and the exact lines to paste into DEVON's .env.
#
#   ./scripts/devon-local.sh
#
# It does every step and stops with a plain explanation if one fails:
#
#   1. Checks Docker
#   2. Writes .env and generates the three local tokens once
#   3. Makes sure the source media directory exists
#   4. Builds and starts the web control plane and the FFmpeg worker
#   5. Waits for health and reports whether execution is actually ready
#   6. Prints DEVON's EditForge lane, and the MCP line for this repo
#
# Safe to run again. It reuses the .env, the volumes, and the tokens you
# already have, so a second run repeats nothing and rotates nothing.

set -uo pipefail

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_DIR"

COMPOSE_FILE="compose.local.yaml"

bold() { printf "\033[1m%s\033[0m\n" "$1"; }
step() { printf "\n\033[38;5;173m[%s/6]\033[0m %s\n" "$1" "$2"; }
ok()   { printf "      \033[38;5;79m*\033[0m %s\n" "$1"; }
warn() { printf "      \033[38;5;179m!\033[0m %s\n" "$1"; }
die()  { printf "\n\033[38;5;203mStopped.\033[0m %s\n\n" "$1"; exit 1; }

secret() {
  if command -v openssl >/dev/null 2>&1; then
    openssl rand -hex 24
  elif command -v python3 >/dev/null 2>&1; then
    python3 -c 'import secrets; print(secrets.token_hex(24))'
  else
    die "Need openssl or python3 to generate the local tokens."
  fi
}

# Fill a variable in .env only when it is present and empty. Never overwrites a
# value you already set, so re-running cannot rotate a token DEVON is holding.
fill_if_blank() {
  local key="$1" value="$2"
  grep -q "^${key}=$" .env 2>/dev/null || return 1
  python3 - "$key" "$value" <<'PYEOF'
import pathlib, sys
key, value = sys.argv[1], sys.argv[2]
p = pathlib.Path(".env")
lines = p.read_text().splitlines()
for index, line in enumerate(lines):
    if line == f"{key}=":
        lines[index] = f"{key}={value}"
        break
p.write_text("\n".join(lines) + "\n")
PYEOF
  return 0
}

env_value() {
  python3 - "$1" <<'PYEOF'
import pathlib, sys
key = sys.argv[1]
for line in pathlib.Path(".env").read_text().splitlines():
    if line.startswith(f"{key}="):
        print(line.split("=", 1)[1].strip())
        break
PYEOF
}

printf "\n"
bold "EditForge — local DEVON stack"
printf "Control plane and FFmpeg worker on this machine. Nothing calls Vercel.\n"

# ---------------------------------------------------------------------------
step 1 "Checking Docker"
# ---------------------------------------------------------------------------
command -v docker >/dev/null 2>&1 || die \
"Docker is not installed. Get Docker Desktop from https://docker.com/get-started
then run this again."
docker compose version >/dev/null 2>&1 || die \
"Docker is installed but 'docker compose' is not available. Update Docker Desktop,
or install the Compose plugin, then run this again."
docker info >/dev/null 2>&1 || die \
"Docker is installed but the engine is not running. Start Docker Desktop and wait
for it to say it is running, then try again."
ok "Docker engine reachable"

# ---------------------------------------------------------------------------
step 2 "Your settings"
# ---------------------------------------------------------------------------
if [ ! -f .env ]; then
  cat > .env <<'ENVEOF'
# EditForge local settings. Private: git ignores this file. Generated by
# scripts/devon-local.sh — see docs/LOCAL_OPERATION.md.

# Where the studio answers on this machine, and how it addresses itself.
EDITFORGE_PORT=3100
EDITFORGE_PUBLIC_URL=http://localhost:3100

# Google is the first browser identity. Add a local OAuth callback for
# http://localhost:3100/api/auth/google/callback in the Google Web client.
GOOGLE_CLIENT_ID=
GOOGLE_CLIENT_SECRET=
EDITFORGE_GOOGLE_ALLOWED_EMAIL=
# Browser session signing. Generated locally and never used as a login value.
EDITFORGE_SESSION_SECRET=
# DEVON's bearer token. This is the value DEVON holds as EDITFORGE_TOKEN.
EDITFORGE_MCP_TOKEN=
# Control plane -> worker. Different value on purpose; DEVON never sees it.
EDITFORGE_WORKER_TOKEN=

# Private source media already on this machine, mounted read-only into the
# catalog and the render worker. Example: /root/Media Assets
EDITFORGE_SOURCE_MEDIA_HOST_DIR=./media

# Studio providers, optional. Empty means /gen-video, /voice and /avatar run
# mock. The DEVON edit lane does not read these.
RUNWAY_API_KEY=
ELEVENLABS_API_KEY=
ELEVENLABS_VOICE_ID=
HEYGEN_API_KEY=
HEYGEN_AVATAR_ID=
HEYGEN_VOICE_ID=
ENVEOF
  ok "Wrote .env"
else
  ok ".env already exists, leaving your settings alone"
fi

for key in EDITFORGE_SESSION_SECRET EDITFORGE_MCP_TOKEN EDITFORGE_WORKER_TOKEN; do
  if fill_if_blank "$key" "$(secret)"; then
    ok "Generated $key"
  fi
done

for key in GOOGLE_CLIENT_ID GOOGLE_CLIENT_SECRET EDITFORGE_GOOGLE_ALLOWED_EMAIL; do
  [ -n "$(env_value "$key")" ] || die \
"$key is missing from .env. Google must be configured before the passwordless
studio can start."
done

for key in EDITFORGE_SESSION_SECRET EDITFORGE_MCP_TOKEN EDITFORGE_WORKER_TOKEN; do
  [ -n "$(env_value "$key")" ] || die \
"$key is missing from .env. Add the line '$key=' and run this again, or set a
value yourself."
done

MCP_TOKEN="$(env_value EDITFORGE_MCP_TOKEN)"
PORT="$(env_value EDITFORGE_PORT)"; PORT="${PORT:-3100}"
PUBLIC_URL="$(env_value EDITFORGE_PUBLIC_URL)"; PUBLIC_URL="${PUBLIC_URL:-http://localhost:$PORT}"

# ---------------------------------------------------------------------------
step 3 "Source media"
# ---------------------------------------------------------------------------
MEDIA_DIR="$(env_value EDITFORGE_SOURCE_MEDIA_HOST_DIR)"; MEDIA_DIR="${MEDIA_DIR:-./media}"
if [ -d "$MEDIA_DIR" ]; then
  ok "Mounting $MEDIA_DIR read-only"
else
  mkdir -p "$MEDIA_DIR" 2>/dev/null && ok "Created $MEDIA_DIR" || warn \
"Could not create $MEDIA_DIR. Point EDITFORGE_SOURCE_MEDIA_HOST_DIR at a folder
that exists, or the stack will refuse to start."
fi

# ---------------------------------------------------------------------------
step 4 "Building and starting"
# ---------------------------------------------------------------------------
printf "      first build takes a few minutes\n"
docker compose -f "$COMPOSE_FILE" up -d --build || die \
"Compose could not bring the stack up. The reason is printed above.
'docker compose -f $COMPOSE_FILE logs' shows what each service said."
ok "web and worker started"

# ---------------------------------------------------------------------------
step 5 "Waiting for health"
# ---------------------------------------------------------------------------
# Read the body whatever the status: /api/health answers 503 when the store or
# worker is degraded, and a degraded studio that is plainly answering must not
# be reported as one that never came up.
HEALTH=""
for _ in $(seq 1 40); do
  HEALTH="$(curl -sS "$PUBLIC_URL/api/health" 2>/dev/null)"
  printf '%s' "$HEALTH" | grep -q '"service":"editforge"' && break
  HEALTH=""
  sleep 3
done
[ -n "$HEALTH" ] || die \
"The studio did not answer on $PUBLIC_URL/api/health.
'docker compose -f $COMPOSE_FILE ps' shows the container states and
'docker compose -f $COMPOSE_FILE logs web' shows why."
ok "Health answered on $PUBLIC_URL"

if printf '%s' "$HEALTH" | grep -q '"executionReady":true'; then
  ok "Execution ready — the worker is reachable and edits will run"
else
  warn "Health answered but executionReady is false. The control plane is up and"
  warn "the worker is not; 'docker compose -f $COMPOSE_FILE logs worker' says why."
fi

# ---------------------------------------------------------------------------
step 6 "DEVON's side"
# ---------------------------------------------------------------------------
cat <<TXT

$(bold "Studio")   $PUBLIC_URL/studio
$(bold "Health")   $PUBLIC_URL/api/health

$(bold "Put these in DEVON's .env") — Meta-Supreme-Apex-Genesis-/.env

  EDITFORGE_URL=$PUBLIC_URL
  EDITFORGE_TOKEN=$MCP_TOKEN

If DEVON itself runs in Docker on this machine, use
http://host.docker.internal:$PORT instead.

$(bold "For this repo's MCP connector"), export before starting Claude Code:

  export EDITFORGE_MCP_URL=$PUBLIC_URL/api/mcp
  export EDITFORGE_MCP_TOKEN=$MCP_TOKEN

Clone voice, full motion and lip sync are not in this stack. Their adapters are
unset, so a command asking for one fails rather than silently skipping. Those
need compose.yaml, a consented identity registry, and a per-job ceiling —
docs/DEVON_EXECUTION.md.

Stop with:  docker compose -f $COMPOSE_FILE down

TXT
